EVERSE-ResearchSoftware/RSQKit

- pages/about.md
A test to see how adding pages works.
> Add about page

- index.md
- pages/your_tasks/licencing_software.md
Adding a disclaimer and the RDM link as credit in "licensing"
> Adding disclaimer and credit section in licensing

- pages/your_tasks/virtual_dev_environments.md
Addresses: https://github.com/EVERSE-ResearchSoftware/RSQKit/pull/35#issuecomment-2371453799
> Simplified Pyton virtual env ecosystem examples

- pages/panosc.md
taken directly from https://panosc.eu
Please review.
> added initial information about PaNOSC cluster

- pages/escape.md
please find a first description of ESCAPE in this PR
> initial escape description

- pages/research_software.md
Added a definition of research software and some discussion.
The link to the life cycle and three tier model uses relative addressing but I don't have the setup to test it.
> Added a definition of research software

- pages/research_software.md
…es directory but all seem to be flattened out at the top level - so a fix for the relative links
> Fixing relative links as any page under pages seems flat

- pages/rs_quality.md
> Adding landing page for RS Quality

- pages/research_software.md
…e to put in RSQKit/page(without the .md ending)
> Final relative addressing fix - I hope

- pages/your_tasks/releasing_code.md
This page provides useful aspects to be considered when creating code releases.
> Add page about how to create code releases

- pages/sshoc.md
From last WP4 call, ie. a reply to:
> provide a high-level description of your science domain/cluster
> and also add a brief description of the software requirements of the
> domain.
@stranak Want to add anything?
> First draft of the SSH cluster description

- index.md
"Reseach" -> "Research" in _Reseach Software Quality Kit_
> Typo in title (!)

- .github/pull_request_template.md
Fixes #115 
* Added a simple pull request template to stimulate consistent PR information
Notes for reviewers:
* This PR template is very minimal. 
* We could consider adding a checkbox to ask people if they have followed the contribution guidelines?
> Simple pull request template

- pages/all_training_resources.md
Fixes: #93 (and a duplicate issue #114).
> Fix the formatting of all training resources page

- pages/your_tasks.md
- pages/your_tasks/TEMPLATE_your_tasks.md
> Exclude your_tasks template from showing up in the list of tasks

- CONTRIBUTING.md
- EDITORS_CHECKLIST.md
- METADATA_GUIDELINES.md
- README.md
- STYLE_GUIDELINES.md
> Style and wording fixes to 'contributing' sections of RSQKit

- pages/contributing/editorial_board.md
> Add filtering contributors by editor role for Editorial Board page

- README.md
- pages/about.md
> Add acknowledgement to RDMKit and ETT in About page

- pages/your_tasks/licensing_software.md
* add REUSE recommendation in case of multiple licenses
> addition of REUSE to license task

- pages/your_tasks/TEMPLATE_your_tasks.md
- pages/your_tasks/codemeta.md
- pages/your_tasks/creating_readthedocs.md
- pages/your_tasks/environmental_sustainability.md
- pages/your_tasks/how_to_make_a_good_readme.md
- pages/your_tasks/languages_frameworks_technologies.md
- pages/your_tasks/licensing_software.md
- pages/your_tasks/readable_code.md
- pages/your_tasks/releasing_code.md
- pages/your_tasks/software_documentation.md
- pages/your_tasks/testing_code.md
- pages/your_tasks/version_control.md
- pages/your_tasks/virtual_dev_environments.md
- pages/your_tasks/zenodo_doi.md
> Fix for related pages not showing

- _data/tool_and_resource_list.yml
Typo and description fixes; removal of duplicates.
> Updates to tool_and_resource_list.yml

- _config.yml
- _data/sidebars/main.yml
- _includes/citation.html
- _layouts/page.html
Add citation info for task pages. Fixes #179.
> Add citation info for task pages automatically

- pages/your_role/TEMPLATE_your_role.md
Create template for Your role pages based on the RDMkit: https://github.com/elixir-europe/rdmkit/blob/master/pages/your_role/TEMPLATE_your_role.md
Fixes #199
> Create template for Your role pages

- _data/sidebars/contributing.yml
- pages/contributing/page_ids.md
Create a page with all page IDs in the contributing section
Fixes #198
> Create a page with all page IDs

- pages/contributing/style_guidelines.md
> Initial draft of page style guidelines

- _data/footer.yml
This fixes https://github.com/EVERSE-ResearchSoftware/RSQKit/issues/34
Notes for reviewers: 
* kept this focused on the content
> Update footer license

- _config.yml
- _includes/topnav.html
> Add social network links and remove twitter

- _data/tool_and_resource_list.yml
Review and update the tools description. Last tool cover was IntelliJ IDEA on line 98.
> Update tool and resource list

- _data/sidebars/main.yml
- _data/tool_and_resource_list.yml
- pages/your_tasks/organising_software_project.md
> Organising software projects task page

- _data/sidebars/main.yml
- pages/your_tasks/cff.md
Before creating a pull request:
- *Please make sure you have checked CONTRIBUTING.md guidelines.*
- *Is there a related issue for the fix you are providing? If not, please consider adding one.*
- *If you are changing files in `data/` or `_includes` folder or `config.yaml` file - please make sure you have discussed this with the maintainers in the relevant issue.*
Fixes #196 
* Added a task that describes why and how to add a CITATION.cff file. 
Notes for reviewers: 
* None
> CITATION.cff task 

- pages/your_tasks/readable_code.md
> Fix a typo in readable_code.md

- _data/tool_and_resource_list.yml
* Add the Prettier code formatter tool
> Add the Prettier code formatter tool

- pages/research_software/life_cycle.md
Before creating a pull request:
- *Please make sure you have checked CONTRIBUTING.md guidelines.*
- *Is there a related issue for the fix you are providing? If not, please consider adding one.*
- *If you are changing files in `data/` or `_includes` folder or `config.yaml` file - please make sure you have discussed this with the maintainers in the relevant issue.*
Fixes #issue_number (*add the relevant issue number*).
* list your changes here
* list another change
* and so on
Notes for reviewers: 
* provide additional information for the reviewers here (if needed)
> adding comment and fixing typo in lifecycle page

- pages/about.md
Fixes #278.
Wording:   
"is heavily inspired and replicating the work"   
-> "is heavily inspired by and replicates the work"
> Improve wording in about.md

- pages/rs_quality/fair_rs.md
> Add FAIR Software Checklist to `fair_rs.md`, issue #112

- _data/tool_and_resource_list.yml
- pages/your_tasks/software_documentation.md
Update software documentation task with better software documentation type classification - based on conversations at deRSE event with @jankapunkt, @c-martinez and @shoaibsufi - see PR #268 and in particular this [comment](https://github.com/EVERSE-ResearchSoftware/RSQKit/pull/268#discussion_r1969877830).
> Update software documentation task

- README.md
- pages/your_tasks/citing_software.md
> Fix related pages in "Citing Software" 

- _data/tool_and_resource_list.yml
- pages/your_tasks/reproducible_software_environments.md
> Add UV tool

- _data/CONTRIBUTORS.yml
* adding my name to the list of contributors
Notes for reviewers:
> adding myself in contributors

- README.md
- _data/footer.yml
- _includes/footer.html
> Add citation info

- pages/your_tasks/organising_software_projects.md
Fix link to citation software page. Fixes #232.
> Fix link to citation software page. Fixes #232.

- _config.yml
- _sass/_bootstrap_variables.scss
- _sass/_custom_variables.scss
Would be good to add the new logo too - maybe we can poll the project colleagues for which one they like best? See #83
> Styling for RSQKit - using EVERSE colours, font, etc.

- _data/tool_and_resource_list.yml
Updating/Correcting tool and resources list, https://github.com/EVERSE-ResearchSoftware/RSQKit/issues/203:
> Correct tool and resources list

- _data/sidebars/main.yml
- _layouts/home.html
- index.md
> Fix search and remove get involved tile on home page

- pages/your_tasks/TEMPLATE_your_tasks.md
- pages/your_tasks/ci_cd.md
- pages/your_tasks/citing_software.md
- pages/your_tasks/code_review.md
- pages/your_tasks/creating_good_readme.md
- pages/your_tasks/documenting_software.md
- pages/your_tasks/documenting_software_readthedocs.md
- pages/your_tasks/improving_environmental_sustainability.md
- pages/your_tasks/languages_tools_infrastructures.md
- pages/your_tasks/licensing_software.md
- pages/your_tasks/organising_software_projects.md
- pages/your_tasks/packaging_releasing_software.md
- pages/your_tasks/releasing_software.md
- pages/your_tasks/reproducible_software_environments.md
- pages/your_tasks/software_documentation.md
- pages/your_tasks/software_identifiers.md
- pages/your_tasks/software_metadata.md
- pages/your_tasks/task_automation_github_actions.md
- pages/your_tasks/task_automation_gitlab_ci_cd.md
- pages/your_tasks/testing_software.md
- pages/your_tasks/writing_readable_code.md
This PR adds a first version of indicators (per https://w3id.org/everse/i/indicators/)
associated with each of the task pages of the RSQKit.
> First round of annotations of indicators

- _data/quality_dimensions.yml
- _data/quality_indicators.yml
- pages/rs_quality/fair_rs.md
It's just a link fix.
Note: the quality indicators and dimensions are automatically added.
> Fixes #387 correcting a link

- _config.yml
- _data/quality_dimensions.yml
- _data/quality_indicators.yml
- _includes/more-information-tiles.html
- pages/contributing/metadata_guidelines.md
- pages/rs_quality.md
- pages/your_tasks/TEMPLATE_your_tasks.md
- pages/your_tasks/ci_cd.md
- pages/your_tasks/citing_software.md
- pages/your_tasks/code_review.md
- pages/your_tasks/computational_workflows.md
- pages/your_tasks/creating_good_readme.md
- pages/your_tasks/documenting_software.md
- pages/your_tasks/documenting_software_readthedocs.md
- pages/your_tasks/improving_environmental_sustainability.md
- pages/your_tasks/languages_tools_infrastructures.md
- pages/your_tasks/licensing_software.md
- pages/your_tasks/organising_software_projects.md
- pages/your_tasks/packaging_releasing_software.md
- pages/your_tasks/releasing_software.md
- pages/your_tasks/reproducible_software_environments.md
- pages/your_tasks/software_documentation.md
- pages/your_tasks/software_identifiers.md
- pages/your_tasks/software_metadata.md
- pages/your_tasks/task_automation_github_actions.md
- pages/your_tasks/task_automation_gitlab_ci_cd.md
- pages/your_tasks/testing_software.md
- pages/your_tasks/using_version_control.md
- pages/your_tasks/writing_readable_code.md
Updates to @kennethrioja's PR #422.
Fixes #417.
Also fixes #438.
> Training preview

- pages/contributing/page_style_guidelines.md
> Add content style guideline of keeping one sentence per line

- pages/research_software_stories/acts_research_software_story.md
Referring to issue #429, I have added subtitles to different sections of the ACTS RS story to make the story even more reader-friendly.
Fixed #429 
- Added subtitles to different sections of the story to make it even more reader-friendly.
> update ACTS RS story
